name: trackizer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  syncfusion_flutter_charts: ^28.2.11
  sleek_circular_slider: ^2.0.1
  font_awesome_flutter: ^10.8.0
  date_picker_timeline: ^1.2.6
  pin_code_fields: ^8.0.1
  provider: ^6.1.4
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  currency_picker: ^2.0.21
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

